      SUBROUTINE F04ADF(A, IA, B, IB, N, M, C, IC, WKSPCE, IFAIL)
C     MARK 2 RELEASE. NAG COPYRIGHT 1972
C     MARK 3 REVISED.
C     MARK 4.5 REVISED

C     DOUBLE PRECISION VERSION WITH COMPLEX
C
C     APPROXIMATE SOLUTION OF A SET OF COMPLEX LINEAR
C     EQUATIONS WITH MULTIPLE RIGHT HAND SIDES.
C     1ST AUGUST 1971
C
      INTEGER P01AAF, ISAVE, IFAIL, I, N, J, M, IA, IC, IB
      DOUBLE PRECISION SRNAME
      COMPLEX*16 A(IA,N), B(IB,M), C(IC,M)
      DOUBLE PRECISION DETR, DETI, WKSPCE(N)
      DATA SRNAME /8H F04ADF /
      ISAVE = IFAIL
      IFAIL = 1
      DO 40 I=1,N
         DO 20 J=1,M
            C(I,J) = B(I,J)
   20    CONTINUE
   40 CONTINUE
      CALL F03AHF(N, A, IA, DETR, DETI, I, WKSPCE, IFAIL)
      IF (IFAIL.EQ.0) GO TO 60
      IFAIL = P01AAF(ISAVE,IFAIL,SRNAME)
      RETURN
   60 CALL F04AKF(N, M, A, IA, WKSPCE, C, IC)
      RETURN
      END
