C     Last change:  HLS  27 Jan 98   10:31 am
      LOGICAL FUNCTION LSAME(CA,CB)
C     TEST IF TWO CHARACTERS ARE ESSENTIALLY THE SAME.
C     THE CHARACTER CB IS ONE OF THE FORTRAN SET.
C     (LOWER AND UPPER CASE LETTERS ARE EQUIVALENT.)
C     THIS IS A SUBPROGRAM FOR THE LEVEL TWO BLAS.
C     REVISED 860623
C     REVISED YYMMDD
C     AUTH=R. J. HANSON, SANDIA NATIONAL LABS.
C
C     THIS SUBPROGRAM IS MACHINE-DEPENDENT.
C     VERSION FOR ANY ASCII MACHINE.
      CHARACTER *1 CA
      CHARACTER *1 CB
      INTEGER IOFF
      DATA IOFF/32/
C     SEE IF THE  CHAR. IN STRING CA EQUALS STRING CB.
      LSAME = CA .EQ. CB
      IF (LSAME) RETURN
C     THE CHARS. ARE NOT IDENTICAL.  NOW CHECK THEM FOR EQUIVALENCE.
      ISHIFT = ICHAR(CA) - IOFF
      IF (ISHIFT.GE.ICHAR('A') .AND. ISHIFT.LE.ICHAR('Z')) THEN
          LSAME = ISHIFT .EQ. ICHAR(CB)
      END IF

      RETURN
      END
